CREATE DATABASE customer_shopping_behavior_db;
USE customer_shopping_behavior_db;

SELECT * FROM customer_behavior limit 20;

ALTER TABLE customer_behavior 
CHANGE `Purchase Amount (USD)` purchase_amount DECIMAL(10,2), 
CHANGE `Item Purchased` item_purchased VARCHAR(100),
CHANGE `Shipping Type` shipping_type VARCHAR(20),
CHANGE `Promo Code Used` promo_code VARCHAR(20),
CHANGE `Previous Purchases` previous_purchases INT,
CHANGE `Payment Method` payment_method VARCHAR(50),
CHANGE `Frequency of Purchases` frequency_of_purchases VARCHAR(20);

ALTER TABLE customer_behavior
CHANGE `Customer ID` customer_id INT,
CHANGE `Age` age TINYINT,
CHANGE `Gender` gender ENUM('Male','Female','Other'),
CHANGE `Category` category VARCHAR(50),
CHANGE `Location` location VARCHAR(100),
CHANGE `Size` size VARCHAR(10),
CHANGE `Color` color VARCHAR(30),
CHANGE `Review Rating` review_rating DECIMAL(2,1);
    
ALTER TABLE customer_behavior
CHANGE `Subscription Status` subscription_status ENUM('Yes','No');

ALTER TABLE customer_behavior
CHANGE `Discount Applied` discount_applied ENUM('Yes','No');

SELECT season FROM customer_behavior
WHERE season NOT IN ('Spring','Summer','Autumn','Winter');

SET SQL_SAFE_UPDATES = 0;

UPDATE customer_behavior
SET season = 
    CASE 
        WHEN LOWER(season) = 'spring' THEN 'Spring'
        WHEN LOWER(season) = 'summer' THEN 'Summer'
        WHEN LOWER(season) = 'autumn' THEN 'Autumn'
        WHEN LOWER(season) = 'winter' THEN 'Winter'
        ELSE NULL
    END;

SET SQL_SAFE_UPDATES = 1;

ALTER TABLE customer_behavior
MODIFY season ENUM('Spring','Summer','Autumn','Winter');

-- Q1. What is the total revenue generated by male vs female customers?
SELECT gender,SUM(purchase_amount) AS revenue 
FROM customer_behavior GROUP BY gender;

-- Q2. Which customer used a distcount still spent more than the average purchase amount?
SELECT customer_id,purchase_amount 
FROM customer_behavior
WHERE discount_applied ='Yes' and purchase_amount>=(SELECT AVG(purchase_amount) FROM customer_behavior);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased , AVG(review_rating) AS `Average Product Rating`
FROM customer_behavior
GROUP BY item_purchased 
ORDER BY AVG(review_rating) DESC LIMIT 5;

-- Q.4 Compare the average purchase amount between standard and express shipping.
SELECT shipping_type ,ROUND(AVG(purchase_amount),2) AS avg_purchase
FROM customer_behavior WHERE shipping_type in('Standard','Express') Group By shipping_type;

-- Q5. Do subsribed customers spend more?Compare average spend and total revenue between subscribes and non-subscribers.
SELECT 
    subscription_status,
    ROUND(AVG(purchase_amount),2) AS avg_spend,
    ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer_behavior
GROUP BY subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discount applied?
SELECT 
    item_purchased,
    ROUND(100 * SUM(discount_applied)/COUNT(*),2) AS discount_percentage
FROM customer_behavior
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q.7 Segment customers into New, Returning, and Loyal based on their total number of previous puchases , and show the count of each segment?
SELECT 
    CASE
        WHEN previous_purchases = 0 THEN 'New'
        WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS segment_count
FROM customer_behavior
GROUP BY customer_segment;

-- Q.8 What are the top 3 most purchased products within each category?
SELECT category, item_purchased, purchase_count
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rn
    FROM customer_behavior
    GROUP BY category, item_purchased
) AS ranked
WHERE rn <= 3
ORDER BY category, purchase_count DESC;

-- Q9. Are customers who are repeat buyers(more than 5 previous purchase) also likely to subscribe?
SELECT 
    CASE WHEN previous_purchases > 5 THEN 'Repeat Buyer' ELSE 'Other' END AS buyer_type,
    ROUND(100 * SUM(subscription_status)/COUNT(*),2) AS subscription_percentage,
    COUNT(*) AS total_customers
FROM customer_behavior
GROUP BY buyer_type;

-- Q10. What is the revenue contibution of each age group?
SELECT
    CASE 
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 45 THEN '36-45'
        ELSE '46+'
    END AS age_group,
    ROUND(SUM(purchase_amount),2) AS total_revenue,
    ROUND(100 * SUM(purchase_amount)/SUM(SUM(purchase_amount)) OVER (),2) AS revenue_percentage
FROM customer_behavior
GROUP BY age_group;